README.md
AdNauseam is a fork of uBlock Origin.
AdNauseam not only blocks ads, it obfuscates browsing data to resist tracking by the online ad industry. To throw ad networks off your trail, AdNauseam can be set to “click” blocked ads, further polluting a users' data profile and frustrating those who engage in bulk surveillance and profiling. The extension’s interactive AdVault feature allows users to visualize and explore all the ads that AdNauseam has captured.
=> Add AdNauseam to list of Firefox extensions

README.md
Fastmail (fastmail.com/) is an Australian found company which its head quarter is in US now. It provides free + paid email services to customers.
=> Add Fastmail as Gmail alternative

README.md
I'm the author of Plausible. I think this list was created before I open-sourced the whole codebase in Sept 2019. Anyways, the project is now [open-source](https://github.com/plausible-insights/plausible) so I thought I'd correct it.
=> Correction: mark plausible as an open-source tool

README.md
http://trackmenot.io/
TrackMeNot is an extension for Firefox and Chrome browsers that helps keep privacy by obfuscating search queries made on various search engines (Google, Yahoo, Bing, etc.).
It makes random search queries to hide what you normally search for and will also make additional queries that are modified from your original one to hide your real intent.
=> Add TrackMeNot to obfuscate search queries

README.md
A practical service that empowers webmaster to self-host open source fonts that normally live at "Google Fonts"
=> Add google-webfonts-helper

README.md
https://codefund.io
AFAIK this is the best alternative out there. Their privacy policy:
https://www.iubenda.com/privacy-policy/47597768
=> Add CodeFund as Google Ads alternative

CONTRIBUTORS.md, README.md
Thanks for putting this repo together. I successfully degoogled last year. I haven't missed Google at all, and I’m happy to help others degoogle as well.
It would be good to provide some resources to justify degoogling. *Why should people go to all this trouble degoogling, when Google products are so convenient?*
I added some news articles, blog posts, and books on the topic that can help people make an informed decision. It’s not an exhaustive library of information about Google, just a selection that highlights some of the issues. I have avoided opinionated statements in this section, and have just provided resources for people to make up their own minds.
When I clip articles to my notes app, I title them with this format, which helps sort the articles: `Source | YYYYMMDD: Title in …
=> Add resources to justify degoogling

README.md
EteSync is a popular sync solution for contacts, calendars and tasks with clients for Android,
iOS, the desktop and the web. Including a DAV bridge to make it compatible with any DAV
complaint client. It's also featured on many other privacy lists.
As I said, it also supports contacts sync, though since there was no such category I didn't add
it, but should I?
Note: I'm the creator of EteSync.
=> Add EteSync to calendar and tasks sync

README.md
Hi!
Thank you for creating this useful lists!
I've added 2FA app for iOS [Tofu](https://github.com/calleerlandsson/Tofu).
Regards.
=> Add Tofu to Mobile Applications/Authenticator

README.md
Instead of "instead messaging" I feel it should be "text/video messaging".
=> Change quick description of Hangouts

yaml/degoogle.yml
For some reason EteSync wasn't listed under contacts (I guess the category was added
after EteSync was already on the list).
EteSync is already under calendar and tasks, this commit adds EteSync under contacts too.
=> EteSync: add the contacts (was already in calendar and tasks)

yaml/degoogle.yml
This makes the link clickable and hides the `(http://` part to make it flow with the text better.
=> Improve meet.jit.si link

yaml/degoogle.yml
Fastmail also provides calendaring services, and no longer uses the "Big M" since it was creating too much confusion.
=> Add Fastmail to calendar section, remove 'big M' #210

yaml/degoogle.yml
Riot has rebranded to Element: https://element.io/previously-riot
=> Riot -> Element (Closes #195)

_build.js
Removes table headers if there are no items with `name`s to add.
Alternatively, could replace with a "No alternatives known" text, up to @tycrek
=> Only add Markdown table headers if there is data to be displayed

yaml/degoogle.yml
This PR references Issue #263.
Sync.com is based in Canada, which is a part of 5-eyes, so it should be labelled as such.
Resources:
https://www.sync.com/about/
https://www.sync.com/download/sync_fact_sheet.pdf
=> Update Sync to include 5-eyes

md/_resources.md
Quote from https://en.wikipedia.org/wiki/VirusTotal
> VirusTotal is a website created by the Spanish security company Hispasec Sistemas. Launched in June 2004, it was acquired by Google Inc. in September 2012.[2][3] The company's ownership switched in January 2018 to Chronicle, a subsidiary of Alphabet Inc..
=> VirusTotal is owned by Google - remove it

yaml/degoogle.yml
https://github.com/tycrek/degoogle/issues/324
Either edit or remove nextcloud from mail provider. Nextcloud is not a mail server, no apps(plugin) in the Nextcloud provided such function either. What it's capable of is as a mail client. There are it's own mail client and rainloop for nextcloud. Not a mail server. The alternative can be, to change the description:
~Now also provides an email service (self-hosted).~ Thanks @je-vv
Nextcloud only provides webmail interface that can be used to access email from various provider. 
https://github.com/nextcloud/mail
https://github.com/pierre-alain-b/rainloop-nextcloud
| …
=> Update degoogle.yml, add clearer description for Nextcloud mail client.

yaml/degoogle.yml
Included a few alternatives including one that we develop (Codename One). Notice that I didn't list the biggest ones: React Native and Xamarin since they are owned by Facebook and Microsoft respectively. I understand those shouldn't be listed from the submission guidelines.
Linked issue: https://github.com/tycrek/degoogle/issues/378
| Include my name in [CONTRIBUTORS.md]                 |  no |
| Any alternatives in this PR have a linked issue      |  yes |
| I am affiliated with this alternative (if applicable)  | yes |
=> Added flutter listing

yaml/degoogle.yml
Thank you for adding ente to this list. This change clarifies that ente has apps for (https://github.com/ente-io/bada-frame) and desktop (https://github.com/ente-io/bhari-frame) too.
Original issue (closed): https://github.com/tycrek/degoogle/issues/380
=> Update available platforms for ente

yaml/browserExtensions.yml
The add-on is no longer available at https://addons.mozilla.org/en-US/firefox/addon/dont-touch-my-tabs/
=> Remove "Don't touch my tabs! (rel=noopener)"

MIRRORS.md
I have recently switched to a new domain, so my mirror's URL has changed, as well.
=> Updated domain

yaml/degoogle.yml
> CTemplar is closing and the last day of operation for this email service will be on May 26 of 2022.
Directly quoted from this CTemplar blog post: https://ctemplar.com/ctemplar-is-shutting-down/
=> remove CTemplar from list of email providers
