- CONTRIBUTORS.md
- README.md
I added the Orgzly app as another Keep app alternative.
> Added Orgzly

- README.md
Qwant is a French company (**9-eyes**).
> Add 9-eyes to Qwant

- README.md
Include [LBRY](https://lbry.io/) as an alternative to Youtube.
> Include LBRY in README.md

- README.md
Add cyber to search alternatives
> Update README.md, Add cyber to search alternatives

- README.md
Also moved Signal as the first Hangouts alternative as it's considered the most trustworthy.
> Added sync.com as an alternative to Google Drive

- README.md
I don't use it myself yet, but Brett Terpstra does:
https://brettterpstra.com/2019/12/30/bretts-favorites-2019/
> Added Fathom

- README.md
Website: https://turtlapp.com/
GitHub: https://github.com/turtl
> Add Turtl as Keep alternative

- CONTRIBUTORS.md
- README.md
Probably the best open alternative to Google Street View right now. Also fixed some spelling mistakes.
> Add Mapillary

- README.md
a secure and usable chat client
> add keybase

- README.md
[GoatCounter](https://www.goatcounter.com/)
> Add GoatCounter analytics

- CONTRIBUTORS.md
- README.md
There were several entries without appropriate `x-eyes` notice. I've added some, not saying there aren't more to be added.
> Added some eyes

- README.md
see https://wiki.openstreetmap.org/wiki/FAQ#Is_it_OpenStreetMap_or_Open_Street_Maps.3F
> Rename OpenStreetMaps to OpenStreetMap

- README.md
https://nuclear.js.org/
https://github.com/nukeop/nuclear
I made it, it's free software.
> Add Nuclear as a Play Music alternative

- README.md
I added an entry for the analytics
PS: I am not at all related to this product but I think it's good :+1:
> add: simple analytics

- README.md
Added 2 projects (ONLYOFFICE and seafile) to the list.
> [UPDATE][Alternatives] ONLYOFFICE and seafile

- README.md
Swisscows Translate
Looks like service does not exists anymore
> [REMOVE] Swisscows Translate

- MIRRORS.md
Added [German repo](https://github.com/arentro/degoogle_german) thanks to arentro!
> Add German language repo to MIRRORS.md

- README.md
Added:
- Porkbun
- Toasted Analytics
Updates:
- Simple Analytics is based in Netherlands, so added 9-eyes
- Fathom is based in Canada, so 5-eyes
_Full disclosure: Toasted Analytics is my own product, I've decided to build it in 2019 because I couldn't find a privacy friendly tool that had the necessary features._
_Company is based in UK, hence the 5-eyes_
Edit: Ecosia has been removed
> Add alternatives and update some eyes

- md/_disclaimer.md
> Updated 'What are 5-eyes, 9-eyes, and 14-eyes?'

- degoogle.yml
Added PinePhone as a Google Pixel alternative.
> Added PinePhone

- .github/ISSUE_TEMPLATE/fix-update-alternative.md
- .github/ISSUE_TEMPLATE/new-alternative.md
- .github/ISSUE_TEMPLATE/other.md
- .github/ISSUE_TEMPLATE/remove-alternative.md
- CONTRIBUTING.md
Updated per discussion in #131 with @onlyjob and @FreddyMarsden.
> Update new-alternative.md per #131

- CONTRIBUTORS.md
- yaml/degoogle.yml
> Add ONLYOFFICE offline download

- yaml/degoogle.yml
Signed-off-by: Adam Miller <admiller@redhat.com>
> add calligra office and art suite

- yaml/degoogle.yml
> Fix Mailfence warrant canary link

- CONTRIBUTORS.md
- yaml/degoogle.yml
> Clarify GrapheneOS description

- yaml/degoogle.yml
> Move FreeTube out of mobile apps section

- yaml/degoogle.yml
Thanks for the great app.
Was quite confused to see twice Gmail, here is a fix.
> doc: clarify Gmail app

- md/_contributing.md
| Any alternatives in this PR have a linked issue       | NA |
> Fix minor spelling error

- yaml/degoogle.yml
> add alternatives for groups

- yaml/degoogle.yml
> Revert "add alternatives for groups"

- yaml/browserExtensions.yml
- yaml/degoogle.yml
| **I have read the guidelines in [CONTRIBUTING.md]**   | yes|
| Include my name in [CONTRIBUTORS.md]                  | yes|
> Edit ghacks (closes #296)

- yaml/degoogle.yml
> Add GalliumOS

- yaml/degoogle.yml
> added over 100 links to open source repos (closes #272)

- CONTRIBUTORS.md
- README.md
> fix: small error

- yaml/degoogle.yml
> [FIX #332] Update EteSync descriptions and apps

- yaml/degoogle.yml
Notally has migrated from the earlier IzzyOnDroid repository to the main F-Droid repository.
| ---------  | - |
| **I have read the guidelines in [CONTRIBUTING.md]**   | Yes |
| Include my name in [CONTRIBUTORS.md]                  | No |
| Any alternatives in this PR have a linked issue       | No |
| I am affiliated with this alternative (if applicable) | Yes|
> Change location of Notally

- _build.js
- yaml/degoogle.yml
Closes #347
I decided to use the green from [the OSI logo](https://opensource.org/) instead of blue, to help differentiate it from the other badges.
Also changed the flow-style from [literal](https://www.yaml.info/learn/quote.html#literal) to [folded](https://www.yaml.info/learn/quote.html#folded) for better readability when in a text editor. I chose ~100-110 characters as the wrap point (I'd recommend GitHub's Unified diff view for comparing this one). If this is undesired or you'd prefer a longer/shorter line, let me know and I can adjust.
> [OTHER] Add repo key to degoogle.yml for open-source projects

- CONTRIBUTORS.md
- yaml/degoogle.yml
> Add Authenticator: Raivo OTP

- CONTRIBUTORS.md
- yaml/degoogle.yml
> Added ProtonCalendar (#362)

- yaml/degoogle.yml
> Update Google Analytics alternative entry

- README.md
- yaml/degoogle.yml
Updated README.md (via the .yaml) to make formatting consistent, regarding any links to GitHub issues.
> Update of README.md

- yaml/degoogle.yml
> (Re)Add CopperheadOS

- MIRRORS.md
The referenced GitHub-user is deleted hence the german fork.
> [FIX] Remove reference to deleted german mirror

- CONTRIBUTORS.md
- yaml/degoogle.yml
[Linked Issue](https://github.com/tycrek/degoogle/issues/387)
> New Alternative: Brave Search

- yaml/degoogle.yml
> Add Nebulo and RethinkDNS + Firewall

- yaml/degoogle.yml
Replaces this PR: https://github.com/tycrek/degoogle/pull/391
> Update Standard Notes domain

- yaml/degoogle.yml
The original issue was opened here: https://github.com/tycrek/degoogle/issues/380
This PR adds ente to the list of mobile app alternatives too. Sorry for not clarifying this previously.
Thanks again!
> Add ente to the list of app based Photos alternatives

- CONTRIBUTORS.md
- md/_lighterSide.md
- md/_resources.md
- yaml/browserExtensions.yml
- yaml/degoogle.yml
Changes:
* Added Techlore vpn toolkit (tools for people who want to use a vpn).
* Added Plexus - A community driven website to allow people to check compatibility on degoogled/microg operating systems.
* Added Surveillance Report - A podcast about security and privacy news.
* Changed The WAN show url to the archive as the previous one lead to a 404 page.
* Added a note about https everywhere almost achiving its goal and telling users to use the https everywhere option inside their browser.
* Added Go Ingocnito -  A guide to security, privacy, and anominity. …
> Added some techlore stuff and a few other changes

- CONTRIBUTORS.md
- yaml/degoogle.yml
I am the author of this alternative.
> Add Piped as YouTube alternative

- yaml/degoogle.yml
Fixes #422, apparently the website moved.
> Update photoprism URL

- MIRRORS.md
I just mirrored this repo over on my Gitea instance and added a link to the file.
> Added my Gitea mirror

- yaml/degoogle.yml
> Update Alpina entry as alternative to GA

- _build.js
- _wiki.js
- package-lock.json
- package.json
| **I have read the guidelines in [CONTRIBUTING.md]**   | yes/no |
| Include my name in [CONTRIBUTORS.md]                  | yes/no |
| I am affiliated with this alternative (if applicable) | yes/no |
> Package update

- md/_lighterSide.md
| **I have read the guidelines in [CONTRIBUTING.md]**   | yes/no |
| Include my name in [CONTRIBUTORS.md]                  | yes/no |
| I am affiliated with this alternative (if applicable) | yes/no |
> feat: style change for testing action

- md/_index.md
> [ignore] misc: bold this text as a test

- md/_license.md
> remove: unnecessary header

- md/_index.md
> misc testing again

- md/_index.md
| **I have read the guidelines in [CONTRIBUTING.md]**   | yes/no |
| Include my name in [CONTRIBUTORS.md]                  | yes/no |
| I am affiliated with this alternative (if applicable) | yes/no |
> eventually this will work

- .github/CODEOWNERS
for file protection going forward
> added CODEOWNERS

- src/md/_index.md
> last test hopefully

- src/md/_index.md
- __I am affiliated with this alternative (if applicable)__: yes
yes/yes/yes/yes/yes/ye
> fix: last test to ensure file actually built

- src/yaml/browserExtensions.yml
Re-do of PR #503 (also see #506). This resolves #460, #461, #462, #463, #464, #465, #466, #467, and #482
> Clean up browser extensions (re-do)

- src/yaml/degoogle.yml
> Remove outdated messaging apps

- src/yaml/degoogle.yml
Co-authored-by: yuuz233 <>
Resolves #493 
> Remove YouTube alternatives

- src/yaml/browserExtensions.yml
- https://www.eff.org/deeplinks/2021/09/https-actually-everywhere
- https://www.eff.org/https-everywhere
Resolves #459
> Remove HTTPS Everywhere

- src/yaml/degoogle.yml
> Fix broken Outline.com link for Fitbit acquisition

- src/yaml/degoogle.yml
> Remove Atom

- src/yaml/browserExtensions.yml
> Add I Still Don't Care About Cookies

- src/yaml/degoogle.yml
Resolves #452. ReVanced is a continuation of YouTube Vanced.
> Replace Vanced with ReVanced

- src/yaml/degoogle.yml
> Remove Blokada

- CONTRIBUTORS.md
- yaml/degoogle.yml
Signed-off-by: Dweb Fan <dwebfan@gmail.com>
https://github.com/tycrek/degoogle/issues/444
> Add lomorage to list of photo alternative applications

- yaml/books.yml
| Include my name in [CONTRIBUTORS.md]                  | yes|
"Life After Google"  by George Gilder is very relevant to  degoogle.
> Add "Life after Google'

- CONTRIBUTORS.md
- yaml/degoogle.yml
> Add Fontsource

- CONTRIBUTORS.md
- yaml/degoogle.yml
I'm the maintainer of [Swetrix](https://swetrix.com). Would be great to see my service in this list.
> Add swetrix.com

- yaml/degoogle.yml
| **I have read the guidelines in [CONTRIBUTING.md]**   | yes|
| I am affiliated with this alternative (if applicable) | yes|
> userTrack was rebranded to UXWizz

- yaml/degoogle.yml
> Added Activepieces as a Google Workflow alternative

- MIRRORS.md
- __I am affiliated with this alternative (if applicable)__: n/a
> Changed Gitea to Cgit

- src/yaml/degoogle.yml
the supabase platform is no longer in alpha, also there are updated guides on self hosting
- __I am affiliated with this alternative (if applicable)__: yes
> chore: update alpha copy on supabase

- src/yaml/degoogle.yml
closes #536. see https://github.com/tycrek/degoogle/issues/123#issuecomment-1821125840
> remove: brick.im
